trigger:
  - main

variables:
# Secrets pull from key vault
- group: kvdevops1

pool:
  name: Contoso

stages:
  - stage: terraform_plan
    displayName: Terraform Plan
    jobs:
      - job: terraform_plan
        displayName: Terraform Plan
        steps:
          - script: |
              export ARM_CLIENT_ID=$(client-id)
              export ARM_CLIENT_SECRET=$(client-secret)
              export ARM_SUBSCRIPTION_ID=$(main-subscription-id)
              export ARM_TENANT_ID=$(tenant-id)
              terraform init
              terraform plan -out=$(System.DefaultWorkingDirectory)/$(Build.BuildId).tfplan
            displayName: Terraform Plan
            name: terraform_plan
            condition: eq(variables.destroy, false)
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(System.DefaultWorkingDirectory)/$(Build.BuildId).tfplan
              artifactName: $(Build.BuildId).tfplan
            displayName: Publish $(Build.BuildId).tfplan
            name: publish_plan